import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { copy as fetchCopy } from "./api.js";

export const FALLBACK = {
  "brand": {
    "programName": "F/A-18 Super Hornet",
    "headerAria": "Boeing F/A-18 Super Hornet home",
    "skipLink": "Skip to content",
    "footerNote": "Demonstration only. Not an official Boeing system.",
    "footerCopy": "© 1995 – 2026 Boeing. All Rights Reserved.",
    "markAlt": "Boeing",
    "documentTitle": "F/A-18 Super Hornet | Boeing"
  },
  "login": {
    "kicker": "Defense > Fighters and bombers",
    "title": "F/A-18 Super Hornet",
    "sub": "Combat-proven, multirole, networked carrier fighter. Sign in to access program systems.",
    "cardTitle": "Sign in",
    "cardSub": "Use your Boeing identity or a demonstration account.",
    "oktaButton": "Sign in with Okta",
    "divider": "or use a demo account",
    "emailLabel": "Email",
    "passwordLabel": "Password",
    "submit": "Continue with demo account",
    "submitting": "Signing in…",
    "hintAuthorizedLabel": "Authorized",
    "hintAuthorizedEmail": "f18.pilot@boeing.com",
    "hintAuthorizedPassword": "HornetReady1",
    "hintVisitorLabel": "Visitor",
    "hintVisitorEmail": "visitor@example.com",
    "hintVisitorPassword": "NoClearance",
    "accessPrompt": "Need an account?",
    "accessLink": "Request access",
    "errorFallback": "Sign-in failed."
  },
  "signup": {
    "kicker": "Defense > Fighters and bombers",
    "title": "Request program access",
    "sub": "Submit your details. A notification is sent to the program access contact.",
    "cardTitle": "Request access",
    "cardSub": "Your request is emailed to the program access contact.",
    "cardSubNotify": "Your request is emailed to {notifyEmail}.",
    "nameLabel": "Name",
    "emailLabel": "Email",
    "organizationLabel": "Organization",
    "optional": "optional",
    "submit": "Submit request",
    "submitting": "Sending…",
    "signinPrompt": "Already have an account?",
    "signinLink": "Sign in",
    "errorFallback": "Request failed."
  },
  "signupSent": {
    "kicker": "Access request",
    "title": "Request sent",
    "sub": "An email with your details was sent to the configured program access contact. They will follow up if access can be granted.",
    "subNotify": "An email with your details was sent to {notifyEmail}. They will follow up if access can be granted.",
    "returnButton": "Return to sign in"
  },
  "success": {
    "kicker": "Program access",
    "title": "You’re signed in",
    "sub": "{name} has access to Super Hornet program systems for this session.",
    "checking": "Checking your session…",
    "emailLabel": "Email",
    "displayNameLabel": "Display name",
    "statusLabel": "Status",
    "statusOk": "Authorized",
    "signOut": "Sign out",
    "openDocs": "Open documentation"
  },
  "denied": {
    "kicker": "Access",
    "title": "This account is not authorized",
    "sub": "Your identity was verified, but this account does not have access to F/A-18 program systems. Request access from your program administrator if you need it.",
    "checking": "Confirming your session…",
    "emailLabel": "Email",
    "statusLabel": "Status",
    "statusBad": "Not authorized",
    "returnButton": "Return to sign in"
  },
  "loggedOut": {
    "kicker": "Session",
    "title": "You have signed out",
    "sub": "Your program session on this device has ended. Sign in again when you need access.",
    "signIn": "Sign in"
  },
  "docs": {
    "title": "F/A-18 Mission Software",
    "kicker": "Technical data",
    "searchPlaceholder": "Search this document",
    "searchLabel": "Search documentation",
    "tocTitle": "On this page",
    "sidebarTitle": "Contents",
    "loading": "Loading documentation…",
    "empty": "No documentation is available.",
    "signOut": "Sign out",
    "prev": "Previous",
    "next": "Next",
    "modules": "Modules",
    "classes": "Classes",
    "files": "Files",
    "pages": "Pages",
    "mockNote": "Using local mock documentation."
  },
  "email": {
    "subject": "Program access request: {name}",
    "body": "A program access request was submitted.\n\nName: {name}\nEmail: {email}\nOrganization: {organization}\nSubmitted: {submitted}\n\nThis message was generated by the F/A-18 Program Access Portal demo.\n",
    "organizationFallback": "(not provided)"
  }
};

/**
 * What: Deep-merge overlay onto base so missing keys keep their fallbacks.
 * Why: A partial /api/copy payload must not blank the UI.
 * Who: CopyProvider when the fetch lands.
 * Where: In-memory copy tree for the SPA.
 * How: Recurse on plain objects; overlay wins when the value is non-null.
 */
function deepMerge(base, overlay) {
  if (!overlay || typeof overlay !== "object" || Array.isArray(overlay)) {
    return base;
  }
  const out = { ...base };
  for (const [key, value] of Object.entries(overlay)) {
    if (
      value &&
      typeof value === "object" &&
      !Array.isArray(value) &&
      base[key] &&
      typeof base[key] === "object" &&
      !Array.isArray(base[key])
    ) {
      out[key] = deepMerge(base[key], value);
    } else if (value != null) {
      out[key] = value;
    }
  }
  return out;
}

/**
 * What: Replace {name}-style placeholders in a copy string.
 * Why: Welcome lines and signup notify sentences interpolate runtime values.
 * Who: Signup, SignupSent, Success (and any page with {notifyEmail} / {name}).
 * Where: Strings from useCopy().
 * How: Regex replace; missing keys stay as the original token.
 */
export function fill(template, vars = {}) {
  /**
   * What: Swap one {token} for a value from vars.
   * Why: String.replace needs a per-match callback.
   * Who: fill (only).
   * Where: Page strings that include {name} or {notifyEmail}.
   * How: Keep the token when the key is missing or null.
   */
  function replaceToken(match, key) {
    return Object.prototype.hasOwnProperty.call(vars, key) && vars[key] != null
      ? String(vars[key])
      : match;
  }
  if (template == null) return "";
  return String(template).replace(/\{(\w+)\}/g, replaceToken);
}

const CopyContext = createContext({ ...FALLBACK, notifyEmail: "" });

/**
 * What: Load /api/copy once and provide the merged tree to the app.
 * Why: Header, footer, and every page share one configurable dictionary.
 * Who: main.jsx wraps <App />; pages call useCopy().
 * Where: SPA root; fetch goes to Flask via the Vite /api proxy.
 * How: Start with FALLBACK; deepMerge the response; set document.title.
 */
export function CopyProvider({ children }) {
  const [copy, setCopy] = useState(() => ({ ...FALLBACK, notifyEmail: "" }));

  useEffect(() => {
    let cancelled = false;
    fetchCopy()
      .then((data) => {
        if (cancelled) return;
        setCopy(deepMerge({ ...FALLBACK, notifyEmail: "" }, data));
      })
      .catch(() => {});
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    const title = copy.brand?.documentTitle || copy.brand?.programName;
    if (title) document.title = title;
  }, [copy]);

  const value = useMemo(() => copy, [copy]);
  return <CopyContext.Provider value={value}>{children}</CopyContext.Provider>;
}

/**
 * What: Read the current copy dictionary (fallbacks until fetch completes).
 * Why: Pages and BrandHeader/Footer must not hardcode user-facing wording.
 * Who: Login, Signup, SignupSent, Success, Denied, LoggedOut, BrandHeader, Footer.
 * Where: Any component under CopyProvider.
 * How: Read the nearest CopyContext so pages share one fetched dictionary.
 */
export function useCopy() {
  return useContext(CopyContext);
}
